#!/usr/bin/env fish

# override fish's command not found messages
function fish_command_not_found
    echo -e "\e[1mError while trying to run the following command\e[0m:" >&2
    echo "--> $argv" >&2
end

function mergevars
    set file_string $argv

    # get all marked fields in the file
    for match in (string match -ra -- '\{\{\{.+?\}\}\}' $file_string)
        set field (string trim -c '{}' -- $match)
        #  we need to reset repl for each iteration so we can test for a field
        #  that evaluated to nothing
        set repl

        set repl (eval printf "%s\n" $field)
        test -z "$repl" && echo -e "\e[1mWarning\e[0m: \"$field\" evaluated to empty string." >&2
        set file_string (string replace -- "$match" "$(string join -- \n $repl)" $file_string)
    end

    # print the result
    string join -- \n $file_string
end

function inject_custom
    # inject the contents of custom_file into target_lines at the specified point
    argparse 'c=' 's=' -- $argv

    set custom_file $_flag_c
    set skel_file $_flag_s
    set target_lines $argv

    # check if a custom file actually exists
    if [ ! -f "$custom" ]
        echo -e "\e[1m$skel_file\e[0m points to a custom file that does not exist." >&2
        echo -e "\tSkipping custom file merging..." >&2
        # getting rid of custom fields as they will otherwise stay as is
        # inside the skel file
        string join -- \n (remove_custom_fields $target_lines)
        return
    end

    # if we do have a custom file: inject its contents
    for line in $target_lines
        if string match -req -- '^\s*\{\{\{custom\}\}\}\s*$' $line
            for custom_line in (cat $custom_file)
                echo $custom_line
            end
        else
            echo $line
        end
    end
end

function safe_write -a write_file

    # only write to file if there were no errors
    set target_lines $argv[2..-1]

    if [ -z "$target_lines" ]
        echo -e "\tSkipping merge for \e[1m$write_file\e[0m..." >&2
        return 1
    else
        mkdir -p (dirname "$write_file")
        string join -- \n $target_lines >"$write_file" || return 1
    end
end

function remove_custom_fields -a lines
    string replace "{{{custom}}}" "" -- $lines
end

function get_meta_line -a line field
    string match -r -- '(?<=%-'$field':).+?(?=-%)' "$line"
end

function process_skel
    argparse C/skip-custom -- $argv
    set skel_file "$argv[1]"

    # parse location line
    set file_string (cat $skel_file)
    if not set location (get_meta_line $file_string[1] LOCATION)
        echo -e "\e[1m$skel_file\e[0m has no line specifying its target location." >&2
        return 1
    end
    # pop location line
    set file_string $file_string[2..]

    # pop custom line if it exists
    if set custom (get_meta_line $file_string[1] CUSTOM)
        set file_string $file_string[2..]
    end

    # get custom variables
    while true
        if set variable (get_meta_line $file_string[1] VARIABLE)
            set -x (string split -f1 = "$variable") (eval printf "%s\n" (string split -m1 -f2 = "$variable")) || return 1
            set file_string $file_string[2..]
        else
            break
        end
    end

    # save permissions of skel file
    set permissions (stat -c "%a" "$skel_file")
    # resolve variables in extracted lines
    set location (eval echo -n $location)
    set custom (eval echo -n $custom)

    # handle the custom file line
    if [ -n "$custom" ] && set -q _flag_skip_custom
        # if there is a custom file line in the file but the skip-custom flag
        # was specified, we need to remove the custom field
        set file_string (remove_custom_fields $file_string)
    else if [ -n "$custom" ]
        # otherwise, try to inject the contents of the custom file
        set file_string (inject_custom -s $skel_file -c $custom -- $file_string) || return 1
    end

    # field substitution
    set file_string (mergevars $file_string) || return 1

    # write $file_string to file
    safe_write "$location" $file_string || return 1
    # copy permissions from skel file to destination
    chmod $permissions "$location" || return 1
end

function prompt -a file
    read -P "About to merge $file. Continue? [Y/n] " -n 1 answer
    set answer (string lower -- $answer)
    test -z "$answer"; and set answer y
    if [ "$answer" = y ]
        return 0
    else
        return 1
    end
end

function main
    argparse -n merge-configs p/prompt d/directory C/skip-custom -- "$argv" || return 1

    if set -q _flag_directory
        set SKEL_FILES_PATH $_flag_directory
    else if set -q MC_SKEL_FILES_PATH
        set SKEL_FILES_PATH $MC_SKEL_FILES_PATH
    else
        set SKEL_FILES_PATH "$HOME/.local/share/skel"
    end

    if [ ! -d "$SKEL_FILES_PATH" ]
        echo -e "\e[1m$SKEL_FILES_PATH\e[0m is not a valid path." >&2
        return 1
    end

    for file in "$SKEL_FILES_PATH"/*
        if set -q _flag_prompt
            prompt "$file" || continue
        end

        process_skel $_flag_skip_custom -- "$file"
    end
end

if not status is-interactive
    main $argv
    exit $status
end
