#!/usr/bin/env fish

argparse -x 'u,f' 'm/manual' 'u/user' 'f/field' 'x/xdo' 'X/Xdo' 'r/recent' -- $argv

test -z $PASS_SUBNAME_SPLIT_CHAR && set PASS_SUBNAME_SPLIT_CHAR '%'
test -z $PASSWORD_STORE_DIR && set PASSWORD_STORE_DIR $HOME/.password-store
test -z $PASS_FALLBACK_USER && set PASS_FALLBACK_USER "User"


# prerequisites
set required_execs pass dmenu
# wayland and X11 specific setup
if [ -n "$WAYLAND_DISPLAY" ]
    set -a required_execs jq wl-copy wtype
    set clip_in wl-copy
    set xytool wtype
else
    set -a required_execs xclip xdotool
    set clip_in xclip -selection clipboard
    set xytool xdotool
end
for exec in $required_execs
    if not command -q $exec
        notify-send "$exec not installed."
        exit 1
    end
end


function wayland_get_focused
    if set -q NIRI_SOCKET
        niri msg --json focused-window
    else if set -q SWAYSOCK
        swaymsg -t get_tree | jq -r '..|try select(.focused == true)'
    end
end


function dotool -a cmd
    # for wayland
    if [ -n "$WAYLAND_DISPLAY" ]
        switch $cmd
            case type
                wtype -- "$argv[2..]"
            case key
                wtype -s 100 -k "$argv[2..]"
            case superup
                wtype -m logo
        end
    # for X11
    else
        switch $cmd
            case type key
                xdotool --clearmodifiers "$argv[2..]"
            case superup
                xdotool keyup Super
        end
    end
end


function get_value -a pass key fallback
    pass show $pass >/dev/null 2>&1 || return 1
    # get the value for $key
    pass field "$key" "$pass" 2>/dev/null | read value || set value "$fallback"
    if [ -n "$value" ]
        echo $value
    else
        return 1
    end
end


function do_type
    test -z "$argv" && return 1
    dotool type "$argv"
end


function xdo_pass_entry -a pass
    set user (get_value $pass "user" "$PASS_FALLBACK_USER") || return 1
    set pass_string (pass show $pass | head -n 1) || return 1
    set field_div (get_value $pass "xdoDiv")
    test -z "$field_div" && set field_div "Tab"
    dotool type $user
    dotool superup
    dotool key (string split " " $field_div)
    dotool superup
    dotool type $pass_string
    dotool superup
    dotool key Return
end


function loop_candidates -a prop
    # loop through candidates and find one that matches $prop
    set candidates
    for password in $argv[2..]
        set barepass (command basename -s .gpg $password)
        if string match -qie "$barepass" $prop
            set -a candidates $password
            continue
        end

        set subs (string split "$PASS_SUBNAME_SPLIT_CHAR" "$barepass")
        if [ ! "$subs" = "$barepass" ]
            for sub in $subs
                if not contains $password $candidates && string match -qie "$sub" $prop
                    set -a candidates $password
                    continue
                end
            end
        end
    end
    string join0 $candidates
end


function handle_candidate -S -a candidate
    # handle identified final candidate in the way specified by cmdline arguments

    # first set access time to mark this candidate for use with -r flag
    touch -a {$PASSWORD_STORE_DIR}/{$candidate}.*

    # -X is a special case, if it is passed, everything else is ignored
    if [ -n "$_flag_Xdo" ]
        xdo_pass_entry $candidate || return 1 && return 0
    end

    # otherwise retrieve requested info
    set info
    if [ -n "$_flag_user" ]
        set info (get_value $candidate "user" "$PASS_FALLBACK_USER")
        or begin
            notify-send "Username for $candidate not found."
            return 1
        end
    else if [ -n "$_flag_field" ]
        # make sure the gpg entry is password-unlocked so dmenu doesn't hang
        pass show $candidate >/dev/null 2>&1 || return 1
        set field (pass field -l $candidate | dmenu)
        if [ -z "$field" ]
            notify-send "No field for $candidate selected."
            return 1
        end
        set info (get_value $candidate "$field")
    else
        # if neither of these flags is present just get the password itself (first line)
        set info (pass show $candidate | head -n 1) || return 1
    end

    # handle info
    if [ -z "$_flag_xdo" ]
        # default: copy to clipboard
        echo -n -- "$info" | $clip_in || return 1
        and notify-send -u low "Copied information from $candidate to clipboard."
        fish -c 'sleep 45 && echo -n "" | '$clip_in & disown
    else
        notify-send -u low "Entering information from $candidate..."
        dotool type "$info" || return 1
    end
end


function interactive_select -a message
    test -n "$message" && notify-send "$message"
    for candidate in $argv[2..]
        printf '%s\n' $candidate
    end | dmenu
end


function get_candidate -S
    set candidates
    # get list of all pass files
    set passes (find $PASSWORD_STORE_DIR -name "*.gpg" -type f -printf "%P\n" | sed 's/\.gpg$//')

    if [ -n "$_flag_manual" ]
        interactive_select "" $passes
        return
    else
        # NOTE: candidates are returned NUL-separated
        # first try by window name
        loop_candidates $win_name $passes | read candidates
        # if we get nothing from that, try by window class
        test -z "$candidates" && loop_candidates $win_class $passes | read candidates
    end

    set candidates (string split0 "$candidates")
    if [ (count $candidates) -gt 1 ]
        interactive_select 'Too many candidates.' $candidates
        return
    else if [ -z "$candidates" ]
        interactive_select 'Nothing found. Please select manually.' $passes
        return
    else
        notify-send "Found $candidates."
        echo -n "$candidates"
        return
    end

end


function main -S
    if [ -n "$_flag_recent" ]
        find "$PASSWORD_STORE_DIR" -name "*.gpg" -type f -printf "%A@\0%P\n" | \
            sort -t "\0" -k1 | tail -n1 | cut -d \0 -f2 | sed 's/\.gpg$//' | read candidate
    else
        set candidate (get_candidate)
    end
    
    if [ -n "$candidate" ]
        handle_candidate $candidate || exit 1
    else
        notify-send 'No password selected.'
        exit 1
    end
end

# get name of currently active window
# in wayland
if [ -n "$WAYLAND_DISPLAY" ]
    set active (wayland_get_focused)
    set win_name "$(echo $active | jq -r '.title')"
    set win_class "$(echo $active | jq -r '.app_id')"
    if [ -z "$win_class" ]
        set win_class (echo $active | jq -r '.class')
    end
else
# in x11
    set active_line (string match -ri '^_NET_ACTIVE_WINDOW\(WINDOW\).+' (xprop -root))
    set active_id (string replace -r '^[^#]+#\s(\S+)' '$1' "$active_line")
    set name_line (string match -r 'WM_NAME\([^)]+\).+' (xprop -id $active_id))
    set class_line (string match -r 'WM_CLASS\([^)]+\).+' (xprop -id $active_id))
    set win_name "$(string match -r '"[^"]+"$' "$name_line")"
    set win_class "$(string match -r '"[^"]+"$' "$class_line")"
end
set win_name (string replace -a ' ' '_' "$win_name")
set win_class (string replace -a ' ' '_' "$win_class")

if not status is-interactive
    main
end
